### ISSUE TITLE
Script evtl nicht vollständig`?

### ISSUE THREAD

**Issue by Baenker** [xCruziX/ioBroker-Creating-Alias#2]
Kann es sein das im Script noch etwas fehlt oder in welcher Zeile definiere ich den Alias bzw den Ursprungs-DP?

Im besagten Thread habe ich ein Beispiel von Dir gefunden. Dort steht ganz unten folgende Zeilen:

let idSource = 'shelly.0.SHSW-1#68BAC3#1.Relay0.Switch';
let idTargetAlias = 'Test.Licht.An';
let room = 'yannick';
let funct = 'licht';

createAlias(idSource,idTargetAlias,room,funct);

**Comment by xcruzix** [comment]
Der Ursprungsdatenpunkt ist dem Beispiel idSource und der Alias der erzeugt wird idTargetAlias.
Aus dem Datenpunkt 'shelly.0.SHSW-1#68BAC3#1.Relay0.Switch' wird der Aliaswert 'Test.Licht.An' erzeugt.

**Comment by Baenker** [comment]
Tut mir Leid ich verstehe die Antwort nicht? In der Scriptdatei muss ich doch irgendwo den Ursprungsdatenpunkt angeben? In welcher Zeile mache ich das? Ich finde die Zeile einfach nicht.

Im Thread habe ich schon verstanden das idSource der Ursprung ist und idTargetAlias der Alias. Nur in dem Script hier auf Github finde ich eben genau die beiden Deklarationen nicht...

**Comment by xcruzix** [comment]
Du kannst beide Werte der Funktion selber übergeben.
Folgendes
createAlias(idSource,idTargetAlias,room,funct);
ist ja der Aufruf der Funktion die im Skript hier auf Github steht.

Du nimmst also das Skript und kopierst es dir in dein eigenes Skript und rufst dann zur Erstellung der Alias Werte die Funktion mit den entsprechenden Informationen auf.
Hab auch eben mal die README angepasst mit 2 Beispielen.

**Comment by Baenker** [comment]
Alles klar jetzt habe ich es auch verstanden. Danke für die Erklärung.
